# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrosetta/interfaces/general/device_manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='instrosetta/interfaces/general/device_manager.proto',
  package='instrosetta.interfaces.general.device_manager.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n3instrosetta/interfaces/general/device_manager.proto\x12\x30instrosetta.interfaces.general.device_manager.v1\"s\n\rServerDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12\x16\n\x0einterface_name\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x16\n\x0e\x64\x65vice_details\x18\x05 \x01(\t\"\'\n\x17GetOnlineServersRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"(\n\x18GetOnlineServersResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"*\n\x1aGetConnectedServersRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x1bGetConnectedServersResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x15RegisterServerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x16RegisterServerResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2\x9c\x04\n\rDeviceManager\x12\xab\x01\n\x10GetOnlineServers\x12I.instrosetta.interfaces.general.device_manager.v1.GetOnlineServersRequest\x1aJ.instrosetta.interfaces.general.device_manager.v1.GetOnlineServersResponse\"\x00\x12\xb4\x01\n\x13GetConnectedServers\x12L.instrosetta.interfaces.general.device_manager.v1.GetConnectedServersRequest\x1aM.instrosetta.interfaces.general.device_manager.v1.GetConnectedServersResponse\"\x00\x12\xa5\x01\n\x0eRegisterServer\x12G.instrosetta.interfaces.general.device_manager.v1.RegisterServerRequest\x1aH.instrosetta.interfaces.general.device_manager.v1.RegisterServerResponse\"\x00\x62\x06proto3')
)




_SERVERDETAILS = _descriptor.Descriptor(
  name='ServerDetails',
  full_name='instrosetta.interfaces.general.device_manager.v1.ServerDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='instrosetta.interfaces.general.device_manager.v1.ServerDetails.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='instrosetta.interfaces.general.device_manager.v1.ServerDetails.device_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface_name', full_name='instrosetta.interfaces.general.device_manager.v1.ServerDetails.interface_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='instrosetta.interfaces.general.device_manager.v1.ServerDetails.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_details', full_name='instrosetta.interfaces.general.device_manager.v1.ServerDetails.device_details', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=220,
)


_GETONLINESERVERSREQUEST = _descriptor.Descriptor(
  name='GetOnlineServersRequest',
  full_name='instrosetta.interfaces.general.device_manager.v1.GetOnlineServersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='instrosetta.interfaces.general.device_manager.v1.GetOnlineServersRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=261,
)


_GETONLINESERVERSRESPONSE = _descriptor.Descriptor(
  name='GetOnlineServersResponse',
  full_name='instrosetta.interfaces.general.device_manager.v1.GetOnlineServersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='instrosetta.interfaces.general.device_manager.v1.GetOnlineServersResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=303,
)


_GETCONNECTEDSERVERSREQUEST = _descriptor.Descriptor(
  name='GetConnectedServersRequest',
  full_name='instrosetta.interfaces.general.device_manager.v1.GetConnectedServersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='instrosetta.interfaces.general.device_manager.v1.GetConnectedServersRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=347,
)


_GETCONNECTEDSERVERSRESPONSE = _descriptor.Descriptor(
  name='GetConnectedServersResponse',
  full_name='instrosetta.interfaces.general.device_manager.v1.GetConnectedServersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='instrosetta.interfaces.general.device_manager.v1.GetConnectedServersResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=392,
)


_REGISTERSERVERREQUEST = _descriptor.Descriptor(
  name='RegisterServerRequest',
  full_name='instrosetta.interfaces.general.device_manager.v1.RegisterServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='instrosetta.interfaces.general.device_manager.v1.RegisterServerRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=431,
)


_REGISTERSERVERRESPONSE = _descriptor.Descriptor(
  name='RegisterServerResponse',
  full_name='instrosetta.interfaces.general.device_manager.v1.RegisterServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='instrosetta.interfaces.general.device_manager.v1.RegisterServerResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=471,
)

DESCRIPTOR.message_types_by_name['ServerDetails'] = _SERVERDETAILS
DESCRIPTOR.message_types_by_name['GetOnlineServersRequest'] = _GETONLINESERVERSREQUEST
DESCRIPTOR.message_types_by_name['GetOnlineServersResponse'] = _GETONLINESERVERSRESPONSE
DESCRIPTOR.message_types_by_name['GetConnectedServersRequest'] = _GETCONNECTEDSERVERSREQUEST
DESCRIPTOR.message_types_by_name['GetConnectedServersResponse'] = _GETCONNECTEDSERVERSRESPONSE
DESCRIPTOR.message_types_by_name['RegisterServerRequest'] = _REGISTERSERVERREQUEST
DESCRIPTOR.message_types_by_name['RegisterServerResponse'] = _REGISTERSERVERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerDetails = _reflection.GeneratedProtocolMessageType('ServerDetails', (_message.Message,), dict(
  DESCRIPTOR = _SERVERDETAILS,
  __module__ = 'instrosetta.interfaces.general.device_manager_pb2'
  # @@protoc_insertion_point(class_scope:instrosetta.interfaces.general.device_manager.v1.ServerDetails)
  ))
_sym_db.RegisterMessage(ServerDetails)

GetOnlineServersRequest = _reflection.GeneratedProtocolMessageType('GetOnlineServersRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETONLINESERVERSREQUEST,
  __module__ = 'instrosetta.interfaces.general.device_manager_pb2'
  # @@protoc_insertion_point(class_scope:instrosetta.interfaces.general.device_manager.v1.GetOnlineServersRequest)
  ))
_sym_db.RegisterMessage(GetOnlineServersRequest)

GetOnlineServersResponse = _reflection.GeneratedProtocolMessageType('GetOnlineServersResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETONLINESERVERSRESPONSE,
  __module__ = 'instrosetta.interfaces.general.device_manager_pb2'
  # @@protoc_insertion_point(class_scope:instrosetta.interfaces.general.device_manager.v1.GetOnlineServersResponse)
  ))
_sym_db.RegisterMessage(GetOnlineServersResponse)

GetConnectedServersRequest = _reflection.GeneratedProtocolMessageType('GetConnectedServersRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCONNECTEDSERVERSREQUEST,
  __module__ = 'instrosetta.interfaces.general.device_manager_pb2'
  # @@protoc_insertion_point(class_scope:instrosetta.interfaces.general.device_manager.v1.GetConnectedServersRequest)
  ))
_sym_db.RegisterMessage(GetConnectedServersRequest)

GetConnectedServersResponse = _reflection.GeneratedProtocolMessageType('GetConnectedServersResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCONNECTEDSERVERSRESPONSE,
  __module__ = 'instrosetta.interfaces.general.device_manager_pb2'
  # @@protoc_insertion_point(class_scope:instrosetta.interfaces.general.device_manager.v1.GetConnectedServersResponse)
  ))
_sym_db.RegisterMessage(GetConnectedServersResponse)

RegisterServerRequest = _reflection.GeneratedProtocolMessageType('RegisterServerRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERSERVERREQUEST,
  __module__ = 'instrosetta.interfaces.general.device_manager_pb2'
  # @@protoc_insertion_point(class_scope:instrosetta.interfaces.general.device_manager.v1.RegisterServerRequest)
  ))
_sym_db.RegisterMessage(RegisterServerRequest)

RegisterServerResponse = _reflection.GeneratedProtocolMessageType('RegisterServerResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERSERVERRESPONSE,
  __module__ = 'instrosetta.interfaces.general.device_manager_pb2'
  # @@protoc_insertion_point(class_scope:instrosetta.interfaces.general.device_manager.v1.RegisterServerResponse)
  ))
_sym_db.RegisterMessage(RegisterServerResponse)



_DEVICEMANAGER = _descriptor.ServiceDescriptor(
  name='DeviceManager',
  full_name='instrosetta.interfaces.general.device_manager.v1.DeviceManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=474,
  serialized_end=1014,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOnlineServers',
    full_name='instrosetta.interfaces.general.device_manager.v1.DeviceManager.GetOnlineServers',
    index=0,
    containing_service=None,
    input_type=_GETONLINESERVERSREQUEST,
    output_type=_GETONLINESERVERSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetConnectedServers',
    full_name='instrosetta.interfaces.general.device_manager.v1.DeviceManager.GetConnectedServers',
    index=1,
    containing_service=None,
    input_type=_GETCONNECTEDSERVERSREQUEST,
    output_type=_GETCONNECTEDSERVERSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterServer',
    full_name='instrosetta.interfaces.general.device_manager.v1.DeviceManager.RegisterServer',
    index=2,
    containing_service=None,
    input_type=_REGISTERSERVERREQUEST,
    output_type=_REGISTERSERVERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICEMANAGER)

DESCRIPTOR.services_by_name['DeviceManager'] = _DEVICEMANAGER

# @@protoc_insertion_point(module_scope)
