# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from instrosetta.interfaces.general import device_manager_pb2 as instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2


class DeviceManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOnlineServers = channel.unary_unary(
        '/instrosetta.interfaces.general.device_manager.v1.DeviceManager/GetOnlineServers',
        request_serializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.GetOnlineServersRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.GetOnlineServersResponse.FromString,
        )
    self.GetConnectedServers = channel.unary_unary(
        '/instrosetta.interfaces.general.device_manager.v1.DeviceManager/GetConnectedServers',
        request_serializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.GetConnectedServersRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.GetConnectedServersResponse.FromString,
        )
    self.RegisterServer = channel.unary_unary(
        '/instrosetta.interfaces.general.device_manager.v1.DeviceManager/RegisterServer',
        request_serializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.RegisterServerRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.RegisterServerResponse.FromString,
        )


class DeviceManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOnlineServers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConnectedServers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterServer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeviceManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOnlineServers': grpc.unary_unary_rpc_method_handler(
          servicer.GetOnlineServers,
          request_deserializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.GetOnlineServersRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.GetOnlineServersResponse.SerializeToString,
      ),
      'GetConnectedServers': grpc.unary_unary_rpc_method_handler(
          servicer.GetConnectedServers,
          request_deserializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.GetConnectedServersRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.GetConnectedServersResponse.SerializeToString,
      ),
      'RegisterServer': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterServer,
          request_deserializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.RegisterServerRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_general_dot_device__manager__pb2.RegisterServerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'instrosetta.interfaces.general.device_manager.v1.DeviceManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
