# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from instrosetta.interfaces.electronics import simple_switch_pb2 as instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2


class SimpleSwitchStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Initialize = channel.unary_unary(
        '/instrosetta.interfaces.electronics.simple_switch.v1.SimpleSwitch/Initialize',
        request_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.InitializeRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.InitializeResponse.FromString,
        )
    self.Shutdown = channel.unary_unary(
        '/instrosetta.interfaces.electronics.simple_switch.v1.SimpleSwitch/Shutdown',
        request_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.ShutdownRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.ShutdownResponse.FromString,
        )
    self.Flip = channel.unary_unary(
        '/instrosetta.interfaces.electronics.simple_switch.v1.SimpleSwitch/Flip',
        request_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.FlipRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.FlipResponse.FromString,
        )
    self.GetState = channel.unary_unary(
        '/instrosetta.interfaces.electronics.simple_switch.v1.SimpleSwitch/GetState',
        request_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.GetStateRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.GetStateResponse.FromString,
        )
    self.SetState = channel.unary_unary(
        '/instrosetta.interfaces.electronics.simple_switch.v1.SimpleSwitch/SetState',
        request_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.SetStateRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.SetStateResponse.FromString,
        )


class SimpleSwitchServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Initialize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Shutdown(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Flip(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimpleSwitchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Initialize': grpc.unary_unary_rpc_method_handler(
          servicer.Initialize,
          request_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.InitializeRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.InitializeResponse.SerializeToString,
      ),
      'Shutdown': grpc.unary_unary_rpc_method_handler(
          servicer.Shutdown,
          request_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.ShutdownRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.ShutdownResponse.SerializeToString,
      ),
      'Flip': grpc.unary_unary_rpc_method_handler(
          servicer.Flip,
          request_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.FlipRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.FlipResponse.SerializeToString,
      ),
      'GetState': grpc.unary_unary_rpc_method_handler(
          servicer.GetState,
          request_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.GetStateRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.GetStateResponse.SerializeToString,
      ),
      'SetState': grpc.unary_unary_rpc_method_handler(
          servicer.SetState,
          request_deserializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.SetStateRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_electronics_dot_simple__switch__pb2.SetStateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'instrosetta.interfaces.electronics.simple_switch.v1.SimpleSwitch', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
