# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from instrosetta.interfaces.light import light_source_pb2 as instrosetta_dot_interfaces_dot_light_dot_light__source__pb2


class LightSourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/instrosetta.interfaces.light.light_source.v1.LightSource/Echo',
        request_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.EchoRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.EchoResponse.FromString,
        )
    self.Connect = channel.unary_unary(
        '/instrosetta.interfaces.light.light_source.v1.LightSource/Connect',
        request_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.ConnectRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.ConnectResponse.FromString,
        )
    self.Disconnect = channel.unary_unary(
        '/instrosetta.interfaces.light.light_source.v1.LightSource/Disconnect',
        request_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.DisconnectRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.DisconnectResponse.FromString,
        )
    self.GetPower = channel.unary_unary(
        '/instrosetta.interfaces.light.light_source.v1.LightSource/GetPower',
        request_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.GetPowerRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.GetPowerResponse.FromString,
        )
    self.SetPower = channel.unary_unary(
        '/instrosetta.interfaces.light.light_source.v1.LightSource/SetPower',
        request_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.SetPowerRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.SetPowerResponse.FromString,
        )


class LightSourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Connect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Disconnect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPower(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPower(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LightSourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.EchoRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.EchoResponse.SerializeToString,
      ),
      'Connect': grpc.unary_unary_rpc_method_handler(
          servicer.Connect,
          request_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.ConnectRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.ConnectResponse.SerializeToString,
      ),
      'Disconnect': grpc.unary_unary_rpc_method_handler(
          servicer.Disconnect,
          request_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.DisconnectRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.DisconnectResponse.SerializeToString,
      ),
      'GetPower': grpc.unary_unary_rpc_method_handler(
          servicer.GetPower,
          request_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.GetPowerRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.GetPowerResponse.SerializeToString,
      ),
      'SetPower': grpc.unary_unary_rpc_method_handler(
          servicer.SetPower,
          request_deserializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.SetPowerRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_light_dot_light__source__pb2.SetPowerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'instrosetta.interfaces.light.light_source.v1.LightSource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
