# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from instrosetta.common import connection_pb2 as instrosetta_dot_common_dot_connection__pb2
from instrosetta.interfaces.data_aquisition import basic_daq_pb2 as instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2


class BasicDaqStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAvailbleDevices = channel.unary_stream(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/GetAvailbleDevices',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAvailbleDevicesRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAvailbleDevicesResponse.FromString,
        )
    self.Connect = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/Connect',
        request_serializer=instrosetta_dot_common_dot_connection__pb2.ConnectRequest.SerializeToString,
        response_deserializer=instrosetta_dot_common_dot_connection__pb2.ConnectResponse.FromString,
        )
    self.Disconnect = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/Disconnect',
        request_serializer=instrosetta_dot_common_dot_connection__pb2.DisconnectRequest.SerializeToString,
        response_deserializer=instrosetta_dot_common_dot_connection__pb2.DisconnectResponse.FromString,
        )
    self.ReadDigital = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/ReadDigital',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.ReadDigitalRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.ReadDigitalResponse.FromString,
        )
    self.ReadAnalog = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/ReadAnalog',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.ReadAnalogRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.ReadAnalogResponse.FromString,
        )
    self.WriteDigital = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/WriteDigital',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.WriteDigitalRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.WriteDigitalResponse.FromString,
        )
    self.WriteAnalog = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/WriteAnalog',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.WriteAnalogRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.WriteAnalogResponse.FromString,
        )
    self.GetDeviceDetails = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/GetDeviceDetails',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDeviceDetailsRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDeviceDetailsResponse.FromString,
        )
    self.GetDigitalOutputs = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/GetDigitalOutputs',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDigitalOutputsRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDigitalOutputsResponse.FromString,
        )
    self.GetDigitalInputs = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/GetDigitalInputs',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDigitalInputsRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDigitalInputsResponse.FromString,
        )
    self.GetAnalogOutputs = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/GetAnalogOutputs',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAnalogOutputsRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAnalogOutputsResponse.FromString,
        )
    self.GetAnalogInputs = channel.unary_unary(
        '/instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq/GetAnalogInputs',
        request_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAnalogInputsRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAnalogInputsResponse.FromString,
        )


class BasicDaqServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAvailbleDevices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Connect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Disconnect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadDigital(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadAnalog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteDigital(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteAnalog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDeviceDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDigitalOutputs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDigitalInputs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAnalogOutputs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAnalogInputs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BasicDaqServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAvailbleDevices': grpc.unary_stream_rpc_method_handler(
          servicer.GetAvailbleDevices,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAvailbleDevicesRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAvailbleDevicesResponse.SerializeToString,
      ),
      'Connect': grpc.unary_unary_rpc_method_handler(
          servicer.Connect,
          request_deserializer=instrosetta_dot_common_dot_connection__pb2.ConnectRequest.FromString,
          response_serializer=instrosetta_dot_common_dot_connection__pb2.ConnectResponse.SerializeToString,
      ),
      'Disconnect': grpc.unary_unary_rpc_method_handler(
          servicer.Disconnect,
          request_deserializer=instrosetta_dot_common_dot_connection__pb2.DisconnectRequest.FromString,
          response_serializer=instrosetta_dot_common_dot_connection__pb2.DisconnectResponse.SerializeToString,
      ),
      'ReadDigital': grpc.unary_unary_rpc_method_handler(
          servicer.ReadDigital,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.ReadDigitalRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.ReadDigitalResponse.SerializeToString,
      ),
      'ReadAnalog': grpc.unary_unary_rpc_method_handler(
          servicer.ReadAnalog,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.ReadAnalogRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.ReadAnalogResponse.SerializeToString,
      ),
      'WriteDigital': grpc.unary_unary_rpc_method_handler(
          servicer.WriteDigital,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.WriteDigitalRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.WriteDigitalResponse.SerializeToString,
      ),
      'WriteAnalog': grpc.unary_unary_rpc_method_handler(
          servicer.WriteAnalog,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.WriteAnalogRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.WriteAnalogResponse.SerializeToString,
      ),
      'GetDeviceDetails': grpc.unary_unary_rpc_method_handler(
          servicer.GetDeviceDetails,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDeviceDetailsRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDeviceDetailsResponse.SerializeToString,
      ),
      'GetDigitalOutputs': grpc.unary_unary_rpc_method_handler(
          servicer.GetDigitalOutputs,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDigitalOutputsRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDigitalOutputsResponse.SerializeToString,
      ),
      'GetDigitalInputs': grpc.unary_unary_rpc_method_handler(
          servicer.GetDigitalInputs,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDigitalInputsRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetDigitalInputsResponse.SerializeToString,
      ),
      'GetAnalogOutputs': grpc.unary_unary_rpc_method_handler(
          servicer.GetAnalogOutputs,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAnalogOutputsRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAnalogOutputsResponse.SerializeToString,
      ),
      'GetAnalogInputs': grpc.unary_unary_rpc_method_handler(
          servicer.GetAnalogInputs,
          request_deserializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAnalogInputsRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_data__aquisition_dot_basic__daq__pb2.GetAnalogInputsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'instrosetta.interfaces.data_aquisition.basic_daq.v1.BasicDaq', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
