# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from instrosetta.interfaces.debugging import echo_pb2 as instrosetta_dot_interfaces_dot_debugging_dot_echo__pb2


class EchoServiceStub(object):
  """The first property of all messages is called "name" and reserved for
  a unique identifier (uid) of the request-response session.
  How the uid is generated is implementation specific and should not be relied on for functionality.

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/instrosetta.common.messages.v1.EchoService/Echo',
        request_serializer=instrosetta_dot_interfaces_dot_debugging_dot_echo__pb2.EchoRequest.SerializeToString,
        response_deserializer=instrosetta_dot_interfaces_dot_debugging_dot_echo__pb2.EchoResponse.FromString,
        )


class EchoServiceServicer(object):
  """The first property of all messages is called "name" and reserved for
  a unique identifier (uid) of the request-response session.
  How the uid is generated is implementation specific and should not be relied on for functionality.

  """

  def Echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=instrosetta_dot_interfaces_dot_debugging_dot_echo__pb2.EchoRequest.FromString,
          response_serializer=instrosetta_dot_interfaces_dot_debugging_dot_echo__pb2.EchoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'instrosetta.common.messages.v1.EchoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
